# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='', primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='', max_length=200)),
                ('votes', models.IntegerField(default=0, help_text='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='', primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='', max_length=200)),
                ('pub_date', models.DateTimeField(help_text='', verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
